# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babysitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('minderType', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('postcode', models.CharField(max_length=7, null=True)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=50, null=True)),
                ('fact1', models.CharField(max_length=140, null=True)),
                ('fact2', models.CharField(max_length=140, null=True)),
                ('fact3', models.CharField(max_length=140, null=True)),
                ('description', models.CharField(max_length=140, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('smoking', models.CharField(max_length=140, null=True)),
                ('driver', models.CharField(max_length=140, null=True)),
                ('car', models.CharField(max_length=140, null=True)),
                ('experience', models.CharField(max_length=140, null=True)),
                ('expAges', models.CharField(max_length=140, null=True)),
                ('prefLoc', models.CharField(max_length=140, null=True)),
                ('verified', models.CharField(blank=True, max_length=8, null=True)),
                ('donator', models.CharField(max_length=140, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('age', models.CharField(max_length=2, null=True)),
                ('max_num', models.IntegerField()),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('fieldOfStudy', models.CharField(max_length=50)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('graduated', models.BooleanField(default=False)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysitters.Babysitter')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refFamily', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysitters.Babysitter')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysitters.Babysitter')),
            ],
        ),
    ]
