# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babysitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('minderType', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('eircode', models.CharField(max_length=7, null=True)),
                ('biography', models.TextField(blank=True, max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('fieldOfStudy', models.CharField(max_length=50)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('graduated', models.BooleanField(default=False)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysitters.Babysitter')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refFamily', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysitters.Babysitter')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysitters.Babysitter')),
            ],
        ),
    ]
