# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babysitter',
            old_name='eircode',
            new_name='postcode',
        ),
    ]
