# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
