# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
