# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0003_babysitter_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
