# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0004_babysitter_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='max_num',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
